services:
  db: # mongodb
    container_name: mongodb
    image: mongo:4.4
    command: mongod --port 27017 --quiet
    expose:
      - "27017"
    volumes:
      - dbdata:/data/db
    networks:
      privnet:
        aliases:
          - db

  free5gc-i-upf-1: # i-upf
    container_name: i-upf-1
    build:
      context: ./nf_upf
      args:
        DEBUG_TOOLS: "false"
    command: bash -c "./upf-iptables.sh && ./upf -c ./config/upfcfg.yaml"
    volumes:
      - ./config/MP/i-upfCfg-1.yaml:/free5gc/config/upfcfg.yaml
      - ./config/iptables/upf-iptables.sh:/free5gc/upf-iptables.sh
    cap_add:
      - NET_ADMIN
    networks:
      privnet:
        aliases:
          - i-upf-1.free5gc.org
        ipv4_address: 10.100.200.101
      mec-net:
        aliases:
          - i-upf-1.mec.org

  free5gc-i-upf-2: # i-upf
    container_name: i-upf-2
    build:
      context: ./nf_upf
      args:
        DEBUG_TOOLS: "false"
    command: bash -c "./upf-iptables.sh && ./upf -c ./config/upfcfg.yaml"
    volumes:
      - ./config/MP/i-upfCfg-2.yaml:/free5gc/config/upfcfg.yaml
      - ./config/iptables/upf-iptables.sh:/free5gc/upf-iptables.sh
    cap_add:
      - NET_ADMIN
    networks:
      privnet:
        aliases:
          - i-upf-2.free5gc.org
        ipv4_address: 10.100.200.102
      mec-net:
        aliases:
          - i-upf-2.mec.org

  free5gc-psa-upf-1: # psa-upf
    container_name: psa-upf-1
    build:
      context: ./nf_upf
      args:
        DEBUG_TOOLS: "false"
    command: bash -c "./upf-iptables.sh && ./upf -c ./config/upfcfg.yaml"
    volumes:
      - ./config/MP/psa-upfCfg-1.yaml:/free5gc/config/upfcfg.yaml
      - ./config/iptables/upf-iptables.sh:/free5gc/upf-iptables.sh
    cap_add:
      - NET_ADMIN
    networks:
      privnet:
        aliases:
          - psa-upf-1.free5gc.org
      n6-net:
        aliases:
          - psa-upf-1.n6.org

  free5gc-psa-upf-2: # psa-upf
    container_name: psa-upf-2
    build:
      context: ./nf_upf
      args:
        DEBUG_TOOLS: "false"
    command: bash -c "./upf-iptables.sh && ./upf -c ./config/upfcfg.yaml"
    volumes:
      - ./config/MP/psa-upfCfg-2.yaml:/free5gc/config/upfcfg.yaml
      - ./config/iptables/upf-iptables.sh:/free5gc/upf-iptables.sh
    cap_add:
      - NET_ADMIN
    networks:
      privnet:
        aliases:
          - psa-upf-2.free5gc.org
      n6-net:
        aliases:
          - psa-upf-2.n6.org

  free5gc-n6gw: # n6gw
    container_name: n6gw
    build:
      context: ./dn_n6gw
      args:
        DEBUG_TOOLS: "false"
    command: bash -c "./n6gw-iptables.sh && sleep infinity"
    volumes: 
      - ./config/iptables/n6gw-iptables.sh:/root/n6gw-iptables.sh
    cap_add:
      - NET_ADMIN
    networks:
      privnet:
        aliases:
          - n6gw.free5gc.org
      n6-net:
        aliases:
          - n6gw.local
        ipv4_address: 10.100.50.10

  free5gc-mec: # mec
    container_name: mec
    build:
      context: ./dn_mec
      args:
        DEBUG_TOOLS: "false"
    command: bash -c "./mec-iptables.sh && sleep infinity"
    volumes:
      - ./config/iptables/mec-iptables.sh:/root/mec-iptables.sh
    cap_add:
      - NET_ADMIN
    networks:
      privnet:
        aliases:
          - mec.free5gc.org
      mec-net:
        aliases:
          - mec.local
        ipv4_address: 10.100.100.10

  free5gc-nrf: # nrf
    container_name: nrf
    build:
      context: ./nf_nrf
      args:
        DEBUG_TOOLS: "false"
    command: ./nrf -c ./config/nrfcfg.yaml
    expose:
      - "8000"
    volumes:
      - ./config/nrfCfg.yaml:/free5gc/config/nrfcfg.yaml
      - ./cert:/free5gc/cert
    environment:
      DB_URI: mongodb://db/free5gc
      GIN_MODE: release
    networks:
      privnet:
        aliases:
          - nrf.free5gc.org
    depends_on:
      - db

  free5gc-amf: # amf
    container_name: amf
    build:
      context: ./nf_amf
      args:
        DEBUG_TOOLS: "false"
    command: ./amf -c ./config/amfcfg.yaml
    expose:
      - "8000"
    volumes:
      - ./config/amfCfg.yaml:/free5gc/config/amfcfg.yaml
      - ./cert:/free5gc/cert
    environment:
      GIN_MODE: release
    networks:
      privnet:
        aliases:
          - amf.free5gc.org
        ipv4_address: 10.100.200.18
    depends_on:
      - free5gc-nrf

  free5gc-ausf: # ausf
    container_name: ausf
    build:
      context: ./nf_ausf
      args:
        DEBUG_TOOLS: "false"
    command: ./ausf -c ./config/ausfcfg.yaml
    expose:
      - "8000"
    volumes:
      - ./config/ausfCfg.yaml:/free5gc/config/ausfcfg.yaml
      - ./cert:/free5gc/cert
    environment:
      GIN_MODE: release
    networks:
      privnet:
        aliases:
          - ausf.free5gc.org
    depends_on:
      - free5gc-nrf

  free5gc-nssf: # nssf
    container_name: nssf
    build:
      context: ./nf_nssf
      args:
        DEBUG_TOOLS: "false"
    command: ./nssf -c ./config/nssfcfg.yaml
    expose:
      - "8000"
    volumes:
      - ./config/nssfCfg.yaml:/free5gc/config/nssfcfg.yaml
      - ./cert:/free5gc/cert
    environment:
      GIN_MODE: release
    networks:
      privnet:
        aliases:
          - nssf.free5gc.org
    depends_on:
      - free5gc-nrf

  free5gc-pcf: # pcf
    container_name: pcf
    build:
      context: ./nf_pcf
      args:
        DEBUG_TOOLS: "false"
    command: ./pcf -c ./config/pcfcfg.yaml
    expose:
      - "8000"
    volumes:
      - ./config/pcfCfg.yaml:/free5gc/config/pcfcfg.yaml
      - ./cert:/free5gc/cert
    environment:
      GIN_MODE: release
    networks:
      privnet:
        aliases:
          - pcf.free5gc.org
    depends_on:
      - free5gc-nrf

  free5gc-smf: # smf
    container_name: smf
    build:
      context: ./nf_smf
      args:
        DEBUG_TOOLS: "false"
    command: ./smf -c ./config/smfcfg.yaml -u ./config/uerouting.yaml
    expose:
      - "8000"
    volumes:
      - ./config/MP/smfCfg.yaml:/free5gc/config/smfcfg.yaml
      - ./config/MP/ueRoutingCfg.yaml:/free5gc/config/uerouting.yaml
      - ./cert:/free5gc/cert
    environment:
      GIN_MODE: release
    networks:
      privnet:
        aliases:
          - smf.free5gc.org
    depends_on:
      - free5gc-nrf
      - free5gc-i-upf-1
      - free5gc-i-upf-2
      - free5gc-psa-upf-1
      - free5gc-psa-upf-2

  free5gc-udm: # udm
    container_name: udm
    build:
      context: ./nf_udm
      args:
        DEBUG_TOOLS: "false"
    command: ./udm -c ./config/udmcfg.yaml
    expose:
      - "8000"
    volumes:
      - ./config/udmCfg.yaml:/free5gc/config/udmcfg.yaml
      - ./cert:/free5gc/cert
    environment:
      GIN_MODE: release
    networks:
      privnet:
        aliases:
          - udm.free5gc.org
    depends_on:
      - db
      - free5gc-nrf

  free5gc-udr: # udr
    container_name: udr
    build:
      context: ./nf_udr
      args:
        DEBUG_TOOLS: "false"
    command: ./udr -c ./config/udrcfg.yaml
    expose:
      - "8000"
    volumes:
      - ./config/udrCfg.yaml:/free5gc/config/udrcfg.yaml
      - ./cert:/free5gc/cert
    environment:
      DB_URI: mongodb://db/free5gc
      GIN_MODE: release
    networks:
      privnet:
        aliases:
          - udr.free5gc.org
    depends_on:
      - db
      - free5gc-nrf

  free5gc-chf: # chf
    container_name: chf
    build:
      context: ./nf_chf
      args:
        DEBUG_TOOLS: "false"
    command: ./chf -c ./config/chfcfg.yaml
    expose:
      - "8000"
    volumes:
      - ./config/chfCfg.yaml:/free5gc/config/chfcfg.yaml
      - ./cert:/free5gc/cert
    environment:
      DB_URI: mongodb://db/free5gc
      GIN_MODE: release
    networks:
      privnet:
        aliases:
          - chf.free5gc.org
    depends_on:
      - db
      - free5gc-nrf
      - free5gc-webui

  free5gc-nef: # nef
    container_name: nef
    build:
      context: ./nf_nef
      args:
        DEBUG_TOOLS: "false"
    command: ./nef -c ./config/nefcfg.yaml
    expose:
      - "8000"
    volumes:
      - ./config/nefCfg.yaml:/free5gc/config/nefcfg.yaml
      - ./cert:/free5gc/cert
    environment:
      GIN_MODE: release
    networks:
      privnet:
        aliases:
          - nef.free5gc.org
    depends_on:
      - db
      - free5gc-nrf

  free5gc-webui: # webui
    container_name: webui
    build:
      context: ./webui
      args:
        DEBUG_TOOLS: "false"
    command: ./webui -c ./config/webuicfg.yaml
    expose:
      - "2121"
    volumes:
      - ./config/webuiCfg.yaml:/free5gc/config/webuicfg.yaml
      - ./cert:/free5gc/cert
    environment:
      - GIN_MODE=release
    networks:
      privnet:
        aliases:
          - webui
    ports:
      - "5000:5000"
      - "2122:2122"
      - "2121:2121"
    depends_on:
      - db
      - free5gc-nrf

  gnb-1:
    container_name: gnb-1
    image: alonza0314/free-ran-ue:latest
    command: ./free-ran-ue gnb -c ./gnbcfg.yaml
    volumes:
      - ./config/MP/gnbCfg-1.yaml:/free-ran-ue/gnbcfg.yaml
    networks:
      privnet:
        ipv4_address: 10.100.200.100
      ran-ue-1:
        ipv4_address: 10.0.3.3
    depends_on:
      - free5gc-amf
      - free5gc-ausf
      - free5gc-chf
      - free5gc-nrf
      - free5gc-nssf
      - free5gc-pcf
      - free5gc-smf
      - free5gc-udm
      - free5gc-udr
      - free5gc-i-upf-1
      - free5gc-i-upf-2
      - free5gc-psa-upf-1
      - free5gc-psa-upf-2

  ue-1:
    container_name: ue-1
    build:
      context: ./ci
      args:
        DEBUG_TOOLS: "false"
    command: ["tail", "-f", "/dev/null"]
    volumes:
      - ./config/MP/ueCfg-1.yaml:/free-ran-ue/uecfg.yaml
      - ./test:/root/test
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    networks:
      privnet:
        ipv4_address: 10.100.200.51
      ran-ue-1:
        ipv4_address: 10.0.3.2
    depends_on:
      - gnb-1

  gnb-2:
    container_name: gnb-2
    image: alonza0314/free-ran-ue:latest
    command: ./free-ran-ue gnb -c ./gnbcfg.yaml
    volumes:
      - ./config/MP/gnbCfg-2.yaml:/free-ran-ue/gnbcfg.yaml
    networks:
      privnet:
        ipv4_address: 10.100.200.200
      ran-ue-2:
        ipv4_address: 10.0.4.3
    depends_on:
      - free5gc-amf
      - free5gc-ausf
      - free5gc-chf
      - free5gc-nrf
      - free5gc-nssf
      - free5gc-pcf
      - free5gc-smf
      - free5gc-udm
      - free5gc-udr
      - free5gc-i-upf-1
      - free5gc-i-upf-2
      - free5gc-psa-upf-1
      - free5gc-psa-upf-2

  ue-2:
    container_name: ue-2
    build:
      context: ./ci
      args:
        DEBUG_TOOLS: "false"
    command: ["tail", "-f", "/dev/null"]
    volumes:
      - ./config/MP/ueCfg-2.yaml:/free-ran-ue/uecfg.yaml
      - ./test:/root/test
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    networks:
      privnet:
        ipv4_address: 10.100.200.52
      ran-ue-2:
        ipv4_address: 10.0.4.2
    depends_on:
      - gnb-2

networks:
  privnet:
    ipam:
      driver: default
      config:
        - subnet: 10.100.200.0/24
    driver_opts:
      com.docker.network.bridge.name: br-free5gc
  
  mec-net:
    ipam:
      driver: default
      config:
        - subnet: 10.100.100.0/24
    driver_opts:
      com.docker.network.bridge.name: br-mec

  n6-net:
    ipam:
      driver: default
      config:
        - subnet: 10.100.50.0/24
    driver_opts:
      com.docker.network.bridge.name: br-n6

  ran-ue-1:
    ipam:
      driver: default
      config:
        - subnet: 10.0.3.0/24
    driver_opts:
      com.docker.network.bridge.name: br-ran-ue-1

  ran-ue-2:
    ipam:
      driver: default
      config:
        - subnet: 10.0.4.0/24
    driver_opts:
      com.docker.network.bridge.name: br-ran-ue-2

volumes:
  dbdata: